# Gradient Descent

In [1]:
import torch
import torch.nn.functional as F

In [2]:
target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]])

In [3]:
x = torch.rand_like(target)
# This means the final scalar will be differentiate by x.
x.requires_grad = True
# You can get gradient of x, after differentiation.

x

tensor([[0.6563, 0.8255, 0.5258],
        [0.6115, 0.7007, 0.3042],
        [0.8216, 0.5399, 0.8989]], requires_grad=True)

In [4]:
loss = F.mse_loss(x, target)

loss

tensor(0.1119, grad_fn=<MseLossBackward0>)

In [5]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold: # loss가 1e-5보다 작은 경우 stop
    iter_cnt += 1
    
    loss.backward() # Calculate gradients.

    x = x - learning_rate * x.grad
    
    # You don't need to aware this now.
    x.detach_()
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target)
    
    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

1-th Loss: 6.7667e-02
tensor([[0.5327, 0.6865, 0.4756],
        [0.5645, 0.6561, 0.3699],
        [0.7946, 0.5977, 0.8992]], requires_grad=True)
2-th Loss: 4.0934e-02
tensor([[0.4365, 0.5784, 0.4366],
        [0.5280, 0.6214, 0.4211],
        [0.7736, 0.6427, 0.8994]], requires_grad=True)
3-th Loss: 2.4763e-02
tensor([[0.3617, 0.4943, 0.4063],
        [0.4995, 0.5944, 0.4608],
        [0.7572, 0.6776, 0.8995]], requires_grad=True)
4-th Loss: 1.4980e-02
tensor([[0.3036, 0.4289, 0.3826],
        [0.4774, 0.5734, 0.4917],
        [0.7445, 0.7048, 0.8996]], requires_grad=True)
5-th Loss: 9.0619e-03
tensor([[0.2583, 0.3780, 0.3643],
        [0.4602, 0.5571, 0.5158],
        [0.7346, 0.7260, 0.8997]], requires_grad=True)
6-th Loss: 5.4819e-03
tensor([[0.2232, 0.3385, 0.3500],
        [0.4468, 0.5444, 0.5345],
        [0.7269, 0.7424, 0.8998]], requires_grad=True)
7-th Loss: 3.3162e-03
tensor([[0.1958, 0.3077, 0.3389],
        [0.4364, 0.5346, 0.5491],
        [0.7209, 0.7552, 0.8998]], requi